name: Enviar saludo
on:
  workflow_dispatch

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar saludo
        run: echo "Hola desde la clase de GitHub actions"

      - name: Mostrar ubicaci√≥n
        run: pwd
